In [58]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# how to create an array

In [2]:
lst=[1,2,3,4,5,6,7,8]

In [3]:
arr=np.array(lst)
print(arr)

[1 2 3 4 5 6 7 8]


In [4]:
arr.size

8

In [5]:
arr.shape

(8,)

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.ndim

1

In [17]:
arr2=np.array(lst).reshape(4,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
arr2.size

8

In [19]:
arr2.shape

(4, 2)

In [20]:
arr2.dtype

dtype('int32')

In [21]:
arr2.ndim

2

In [23]:
arr3=np.array([1,2,3,4,4])
print(arr3.dtype)

int32


# Creating different types of arrays

arange()

In [24]:
arr=np.arange(1,7,2)
arr

array([1, 3, 5])

linspace()

In [28]:
arr=np.linspace(1,7,3)
arr

array([1., 4., 7.])

zeros()

In [29]:
arr=np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

ones()

In [32]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.ones((3,3),dtype=int)*6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

Identity Matrix

In [35]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(6,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

full()

In [37]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

full_like()

In [39]:
arr=np.arange(18).reshape(2,9)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [41]:
np.full_like(arr,10+3j,dtype=complex)

array([[10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j,
        10.+3.j, 10.+3.j],
       [10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j, 10.+3.j,
        10.+3.j, 10.+3.j]])

zeros_like

In [42]:
np.zeros_like(arr)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones_like

In [44]:
np.ones_like(arr)*8

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

reshape

In [45]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
arr

array([1, 2, 3, 4, 5, 6])

np.shape=()

In [51]:
arr2=np.array([1,2,4,6,7,9])
arr2

array([1, 2, 4, 6, 7, 9])

In [53]:
arr2.shape=(2,3)

In [54]:
arr2

array([[1, 2, 4],
       [6, 7, 9]])

In [55]:
arr2

array([[1, 2, 4],
       [6, 7, 9]])

## Transpose

In [56]:
arr2.T

array([[1, 6],
       [2, 7],
       [4, 9]])

## Creating an array

In [ ]:
np.array()
np.arange(start,stop,step)
np.linspace(start,stop,no of values)
np.eye(rows,cols,dtype=int)
np.zeros((rows,cols),dtype=int)
np.zeros_like(arr)
np.ones((rows,cols),dtype=int)
np.ones_like(arr)
np.full((rows,cols),value)
np.full_like(arr,value)

## Creating an array of random values

In [60]:
from numpy import random

In [ ]:
random.random(value)
random.rand(rows,cols)
random.seed(random state)
random.normal(mean,std,size)
random.randint(start,stop,no of values)

In [1]:
from numpy import  random

In [24]:
arr=random.randint(2,10,18).reshape(3,6)
arr

array([[3, 2, 5, 8, 5, 6],
       [2, 9, 9, 4, 7, 5],
       [7, 2, 5, 6, 9, 2]])

In [4]:
arr[0]

array([6, 8, 7, 3, 5, 7])

In [5]:
arr[0,0]

6

In [6]:
arr[2,4]

4

In [7]:
arr[1:2,1:5]

array([[5, 7, 8, 6]])

In [25]:
arr

array([[3, 2, 5, 8, 5, 6],
       [2, 9, 9, 4, 7, 5],
       [7, 2, 5, 6, 9, 2]])

In [28]:
import numpy as np

In [29]:
np.diag(arr)

array([3, 9, 5])

In [30]:
np.diag([9,8,7])

array([[9, 0, 0],
       [0, 8, 0],
       [0, 0, 7]])

In [9]:
arr[0:2,3:7]

array([[3, 5, 7],
       [8, 6, 8]])

In [14]:
from numpy import random

In [31]:
arr=random.randint(12,50,64).reshape(4,4,4)

In [32]:
arr

array([[[21, 21, 12, 33],
        [12, 39, 25, 18],
        [42, 21, 47, 37],
        [14, 16, 25, 31]],

       [[37, 25, 37, 35],
        [42, 15, 22, 18],
        [26, 13, 32, 16],
        [35, 42, 28, 39]],

       [[22, 15, 37, 28],
        [24, 44, 49, 15],
        [48, 38, 16, 37],
        [46, 36, 40, 15]],

       [[27, 33, 23, 43],
        [48, 15, 45, 45],
        [49, 40, 48, 13],
        [18, 38, 34, 43]]])

In [22]:
arr[0,1,1]

48

In [21]:
arr[0]

array([[19, 48, 12, 14],
       [43, 48, 43, 49],
       [15, 14, 46, 26],
       [28, 43, 49, 44]])

In [33]:
arr

array([[[21, 21, 12, 33],
        [12, 39, 25, 18],
        [42, 21, 47, 37],
        [14, 16, 25, 31]],

       [[37, 25, 37, 35],
        [42, 15, 22, 18],
        [26, 13, 32, 16],
        [35, 42, 28, 39]],

       [[22, 15, 37, 28],
        [24, 44, 49, 15],
        [48, 38, 16, 37],
        [46, 36, 40, 15]],

       [[27, 33, 23, 43],
        [48, 15, 45, 45],
        [49, 40, 48, 13],
        [18, 38, 34, 43]]])

In [34]:
arr[2:3,1:3,1:3]

array([[[44, 49],
        [38, 16]]])

In [35]:
arr[::,::,2:]

array([[[12, 33],
        [25, 18],
        [47, 37],
        [25, 31]],

       [[37, 35],
        [22, 18],
        [32, 16],
        [28, 39]],

       [[37, 28],
        [49, 15],
        [16, 37],
        [40, 15]],

       [[23, 43],
        [45, 45],
        [48, 13],
        [34, 43]]])

In [37]:
arr.size

64

In [38]:
arr2=arr.reshape(8,8)

In [39]:
arr2

array([[21, 21, 12, 33, 12, 39, 25, 18],
       [42, 21, 47, 37, 14, 16, 25, 31],
       [37, 25, 37, 35, 42, 15, 22, 18],
       [26, 13, 32, 16, 35, 42, 28, 39],
       [22, 15, 37, 28, 24, 44, 49, 15],
       [48, 38, 16, 37, 46, 36, 40, 15],
       [27, 33, 23, 43, 48, 15, 45, 45],
       [49, 40, 48, 13, 18, 38, 34, 43]])

In [ ]:
ravel()----convert 2D / 3D array into 1D array it does make changes in the existing array  it returns new object

In [43]:
arr3=arr.ravel()

In [44]:
arr3

array([21, 21, 12, 33, 12, 39, 25, 18, 42, 21, 47, 37, 14, 16, 25, 31, 37,
       25, 37, 35, 42, 15, 22, 18, 26, 13, 32, 16, 35, 42, 28, 39, 22, 15,
       37, 28, 24, 44, 49, 15, 48, 38, 16, 37, 46, 36, 40, 15, 27, 33, 23,
       43, 48, 15, 45, 45, 49, 40, 48, 13, 18, 38, 34, 43])

In [45]:
arr3.ndim

1

In [46]:
arr3

array([21, 21, 12, 33, 12, 39, 25, 18, 42, 21, 47, 37, 14, 16, 25, 31, 37,
       25, 37, 35, 42, 15, 22, 18, 26, 13, 32, 16, 35, 42, 28, 39, 22, 15,
       37, 28, 24, 44, 49, 15, 48, 38, 16, 37, 46, 36, 40, 15, 27, 33, 23,
       43, 48, 15, 45, 45, 49, 40, 48, 13, 18, 38, 34, 43])

In [47]:
arr

array([[[21, 21, 12, 33],
        [12, 39, 25, 18],
        [42, 21, 47, 37],
        [14, 16, 25, 31]],

       [[37, 25, 37, 35],
        [42, 15, 22, 18],
        [26, 13, 32, 16],
        [35, 42, 28, 39]],

       [[22, 15, 37, 28],
        [24, 44, 49, 15],
        [48, 38, 16, 37],
        [46, 36, 40, 15]],

       [[27, 33, 23, 43],
        [48, 15, 45, 45],
        [49, 40, 48, 13],
        [18, 38, 34, 43]]])

In [41]:
arr2.ravel()

array([21, 21, 12, 33, 12, 39, 25, 18, 42, 21, 47, 37, 14, 16, 25, 31, 37,
       25, 37, 35, 42, 15, 22, 18, 26, 13, 32, 16, 35, 42, 28, 39, 22, 15,
       37, 28, 24, 44, 49, 15, 48, 38, 16, 37, 46, 36, 40, 15, 27, 33, 23,
       43, 48, 15, 45, 45, 49, 40, 48, 13, 18, 38, 34, 43])

In [48]:
arr3

array([21, 21, 12, 33, 12, 39, 25, 18, 42, 21, 47, 37, 14, 16, 25, 31, 37,
       25, 37, 35, 42, 15, 22, 18, 26, 13, 32, 16, 35, 42, 28, 39, 22, 15,
       37, 28, 24, 44, 49, 15, 48, 38, 16, 37, 46, 36, 40, 15, 27, 33, 23,
       43, 48, 15, 45, 45, 49, 40, 48, 13, 18, 38, 34, 43])

In [49]:
arr4=arr3.reshape(4,4,4)

In [50]:
arr4

array([[[21, 21, 12, 33],
        [12, 39, 25, 18],
        [42, 21, 47, 37],
        [14, 16, 25, 31]],

       [[37, 25, 37, 35],
        [42, 15, 22, 18],
        [26, 13, 32, 16],
        [35, 42, 28, 39]],

       [[22, 15, 37, 28],
        [24, 44, 49, 15],
        [48, 38, 16, 37],
        [46, 36, 40, 15]],

       [[27, 33, 23, 43],
        [48, 15, 45, 45],
        [49, 40, 48, 13],
        [18, 38, 34, 43]]])

create 1D array----np.random.randint(start,stop,values)

indexing and slicing is same like list or datastruc

arr[]

arr[start:stop:step]

create 2D array----np.random.randint(start,stop,values).reshape(rows,cols)

indexing---arr[rows,cols]

slicing----[rows slicing:cols slicing]----arr[start:stop:step,start:stop:step]



create 3D array----np.random.randint(start,stop,values).reshape(repetitions,rows,cols)

indexing---arr[array index,rows,cols]

slicing----[arrays slicing:rows slicing:cols slicing]----arr[start:stop:step,start:stop:step,start:stop:step]



convert  1D 2D 3D-----arr.reshape()

convert 2D or 3D to 1D----arr.ravel()

# Concatenation

Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis. The function takes the following parameters. numpy.concatenate((a1, a2, ...), axis)

concatenate two or more arrays along the rows (top-down) or along the columns (left-right)

To concatenate along the rows number of columns should be the same in both the arrays.

To concatenate along the columns the number of rows should be the same in both the arrays.

### np.concatenate((arr_1,arr_2),axis=0)

In [ ]:
# axis=0- It reads top to bottom==row
# axis=1- It reads left to right==col

In [70]:
arr1=np.random.randint(1,10,8).reshape(2,4)
arr2=np.random.randint(11,30,8).reshape(2,4)


In [71]:
arr1

array([[5, 4, 6, 2],
       [9, 5, 7, 5]])

In [72]:
arr2

array([[21, 19, 12, 19],
       [14, 27, 15, 12]])

In [58]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  9,  6,  7],
       [ 8,  9,  8,  6],
       [26, 28, 24, 16],
       [21, 29, 27, 28]])

In [73]:
np.concatenate((arr2,arr1),axis=0)

array([[21, 19, 12, 19],
       [14, 27, 15, 12],
       [ 5,  4,  6,  2],
       [ 9,  5,  7,  5]])

In [59]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  9,  6,  7, 26, 28, 24, 16],
       [ 8,  9,  8,  6, 21, 29, 27, 28]])

In [60]:
arr1=np.random.randint(1,10,8).reshape(2,4)
arr2=np.random.randint(11,30,18).reshape(3,6)


In [61]:
arr1

array([[2, 9, 3, 8],
       [3, 6, 5, 7]])

In [62]:
arr2

array([[20, 16, 27, 26, 12, 12],
       [29, 16, 26, 11, 16, 20],
       [14, 19, 27, 13, 19, 19]])

In [64]:
np.concatenate((arr1,arr2),axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 6

In [65]:
arr=np.arange(6)
arr_2=np.arange(10,18)

In [66]:
arr

array([0, 1, 2, 3, 4, 5])

In [67]:
arr_2

array([10, 11, 12, 13, 14, 15, 16, 17])

In [69]:
np.concatenate((arr,arr_2))

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 16, 17])

In [74]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


# operations on matrices

1)multiplication---scalar product=normal multiplication--Element by element multiplication=arr*5 ,arr*arr2

                  dot product=matrix multiplication=number of the columns in the first array should be equal to the number                                     
                               of rows in the second array.----### np.dot(arr1,arr2)

2)determinant---np.linalg.det(arr)

3)np.sum(arr,axis=0/1)....0=row/vertical axis     1=col/horizontal axis

4)np.max(arr,axis=0/1)

5)np.min(arr,axis=0/1)

6)np.mean(arr,axis=0/1)

7)np.median(arr,axis=0/1)

8)np.percentile(arr,value of percentile)

9)np.where(condition) --or--np.where((cond1)&(cond2))--It returns the indexes of all the elements where the condition is satisfied

  np.where(condition,x,y)If the condition is True x is the result and if the condition is False then y is the result
    np.where(arr>60,60,np.where(arr<30,30,arr))

10)np.argwhere(array)----indexes of all element it returns array object

11)np.argmax(array)----indexes of max value---It reads the array as a 1-D array(np.ravel()) and accordingly returns the index.
We can get the index of the maximum value along the axes.

12)np.argmin(array)----indexes of min value

13)np.sort(arr)--ascending      descending---np.sort(arr)[::-1]
    
    In a 2-D array np.sort() sorts each row in ascending order by default
      
        decending---np.sort(arr)[::,::-1]
        
              

We use bitwise logical operator

arr[arr>20]

arr[(arr>40)|(arr<70)]

Array is mutable. It means we can change the values.---arr[index]=the value we want to put

## Missing values in an array.----np.nan()
The datatype of np.nan is float
### check how many missing values---np.isnan(arr).sum() or arr[np.isnan(arr)].size

## convert the datatype of the elements of an array----as nan cannot convert int value it can covert only float
arr.astype(float)

## iterate over an array
1D array---same using loop like list

2D array--- it returns each row after each iteration

             # Get all the elements one by one from a 2-D array using loop

for i in arr:

    for j in i:
    
        print(j)
        
or

for i in arr.ravel():

     print(i)


### np.nditer(arr)---returns an iterator object----is use for to iterate elements one by one in 2D and 3Darray

for i in np.nditer(arr):

     print(i)

## broadcasting--when we perform operations of 2 different shape it matchs the shape to perform the element by element operations.

it describes how numpy treats array with diff shapes during arithmetic operation

array  broadcasting array creates an shape automatically

the arrays either side should  be same row or col



## views and copies

views--- same like shallow copy 

         arr.view()---array id diff but if u made change it will affect the original array
         
copy---deep copy         
     
       arr.copy()---